<a href="https://colab.research.google.com/github/vijaygwu/classideas/blob/main/MatrixFactDense.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Sample user-item interaction matrix (ratings)
R = np.array([
    [5, 3, 0, 1],
    [4, 0, 0, 1],
    [1, 1, 0, 5],
    [1, 0, 0, 4],
    [0, 1, 5, 4],
])

# Perform SVD
U, sigma, Vt = np.linalg.svd(R, full_matrices=False)

print("User embeddings (dense vectors):")
print(U)

print("\nItem embeddings (dense vectors):")
print(Vt.T)


User embeddings (dense vectors):
[[-0.43689593 -0.66924125  0.29627751 -0.48637475]
 [-0.29717498 -0.44308727  0.05015708  0.79591123]
 [-0.51589728  0.13631518 -0.54893193 -0.28612203]
 [-0.39999635  0.11077382 -0.48349385  0.20569271]
 [-0.54282768  0.5700326   0.61205501  0.0760895 ]]

Item embeddings (dense vectors):
[[-0.47488998 -0.78203025  0.17212379  0.36507752]
 [-0.26234348 -0.20891356  0.25224247 -0.907692  ]
 [-0.3005118   0.45754472  0.81089006  0.20688838]
 [-0.78444124  0.36801718 -0.49920382  0.00329281]]
